services:
  - type: web
    name: dropvoice-token-server
    env: node
    rootDir: server
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 10000
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
