// This file is generated by FlutterFire CLI.
// Run: flutterfire configure --project=drpovoice
//
// TODO: Run the command above after Firebase CLI is installed.
// The app will NOT compile until this file is populated.
//
// Steps:
// 1. firebase login
// 2. flutterfire configure --project=drpovoice --platforms=android,ios
// This will overwrite this file with real values.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Replace these placeholder values with real ones from:
/// https://console.firebase.google.com/project/drpovoice/settings/general/
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DROPVOICE does not support Web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for platform: $defaultTargetPlatform',
        );
    }
  }

  // ─── REPLACE THESE PLACEHOLDERS WITH REAL VALUES ─────────────────────────
  // Run: flutterfire configure --project=drpovoice

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW9MEW0JMOCk0AWtWzUoeU72uo4orD7TM',
    appId: '1:886598137672:android:c1fa5d4faf12e426bc657d',
    messagingSenderId: '886598137672',
    projectId: 'drpovoice',
    storageBucket: 'drpovoice.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuIlnpvYu7qT0NRUwFWzv_rd2zr6lJWh0',
    appId: '1:886598137672:ios:1125e03f7eb64950bc657d',
    messagingSenderId: '886598137672',
    projectId: 'drpovoice',
    storageBucket: 'drpovoice.firebasestorage.app',
    iosBundleId: 'com.dropvoice.dropvoice',
  );
}
